### ISSUE TITLE
Create a branch against symfony 3.0.x

### ISSUE THREAD

**Issue by dawehner** [symfony-cmf/Routing#123]
Drupal tries to continuously figure out whether an update to 3.0.x breaks.
This is done in order to be able to update to 3.0.x at some point,
because the support cycle of Drupal will be much longer than 2.7 itself.

This means that also symfony-cmf/Routing has to be made compatible with 3.0.x at some point.

Do you plan to open a branch which have the required changes?

**Comment by WouterJ** [comment]
I've created a PR which adds it as an failure-allowed test job. At the moment, it seems like the dependencies can't be installed.

Meanwhile, 2.7 tests will now have propper deprecation errors. We can try to make things 3.0.* compatible and if we can't get it working for both 3.0.* and 2.3.* (or need difficult things), we should maybe create a 2.0-dev branch that's compatible with 2.7 and 3.0 (I don't expect us to be able to have 2.3 *and* 3.0 compatibility).

**Comment by dawehner** [comment]
I'm curious what the plans are now basically 9 months later :)

**Comment by WouterJ** [comment]
The plan is to release CMF 1.3 soon (before end of the year at least) and then start working on CMF 2.0. CMF 1.3 will support 2.x (and some components might also support Symfony 3.0). CMF 2.0 will require PHP 5.5 and Symfony 2.8|3.*. For bigger bundles, it's almost impossible to have 2.3 - 2.7 support while also supporting 3.0.

This means that CMF 1.3 will have a longer support time, until Symfony 2.7 reaches eom.

**Comment by dawehner** [comment]
From just looking at routing this seems to be one of the potential 2.7|3
candidates? Honestly, at least for Drupal, we will try to switch to 2.8 as
soon as possible and don't use any deprecated stuff,
so I guess we would be totally fine with that limitation

**Comment by WouterJ** [comment]
Yes, indeed, the Routing component does support 3.0 (I commented a generic plan, not knowing I was commenting on a Routing issue): https://github.com/symfony-cmf/Routing/blob/master/composer.json

**Comment by dawehner** [comment]
Ah I was imply not on master but on some older stable release. Thank you

**Comment by dbu** [comment]
the upcoming 1.4 release of routing will be compatible with symfony 3, see https://github.com/symfony-cmf/Routing/blob/master/composer.json
