### ISSUE TITLE
Are you aware of the test dependencies?

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/Routing#128]
Just a quick "FYI", your test currently only test against different versions of `symfony/routing`. All other installed components will be the latest version (which is 2.7-dev now).

I'm not sure if that's what you were thinking you were testing and if you like this.

**Comment by dbu** [comment]
erm no, was not aware. i guess we should fix that and just require symfony/symfony in the tests. (although that would hide dependency mistakes if we miss to require some symfony package - should we have one build without explicit composer require call?)

**Comment by dbu** [comment]
fixed in #129
