### ISSUE TITLE
New cmf_routing.pre_dynamic_generate overrides the route name

### ISSUE THREAD

**Issue by luishdez** [symfony-cmf/Routing#134]
Now all my {{ paths(...) }}  try to load 'cmf_routing.pre_dynamic_generate' instead the original name of the route.

I found that the route is being override by the event name

https://github.com/symfony-cmf/Routing/blob/master/DynamicRouter.php#L174

```php
    public function generate($name, $parameters = array(), $referenceType = false)
    {
        if ($this->eventDispatcher) {
            $event = new RouterGenerateEvent($name, $parameters, $referenceType);
            $this->eventDispatcher->dispatch(Events::PRE_DYNAMIC_GENERATE, $event);
            $name = $event->getName(); <------ 
            $parameters = $event->getParameters();
            $referenceType = $event->getReferenceType();
        }
        return $this->getGenerator()->generate($name, $parameters, $referenceType);
    }
```

Note: That getName() method in event for Symfony 3.0 is deprecated so I guess this will work with 3.0

**Comment by dbu** [comment]
oh f... sorry for that one. very stupid, we run into a name clash about
"name"

i think the only sane solution is to call our thing routeName and
setRouteName / getRouteName. luckily there is no release yet of this
version.

can you do a pull request to adjust RouterGenerateEvent and the
DynamicRouter accordingly? if not, i can do that soonish.

**Comment by luishdez** [comment]
Sure no problem! 

Checking the event I see that this is the name of the route or an instance of Route. Shouldn't we call this just `route` ? getRouteName() and getting a route instance doesn't seem very logic.

```php
    /**
     * The name of the route or the Route instance to generate.
     *
     * @var string|Route
     */
    private $name;
```

**Comment by dbu** [comment]
indeed, forgot about that. yes, very good point. lets call this getRoute
then.
