### ISSUE TITLE
Misleading error msg, but easy to solve

### ISSUE THREAD

**Issue by petforsberg** [symfony-cmf/Routing#142]
Hi,

I get circular routing error - (routing -> routing_dev -> my bundle's annotations -> routing_dev ) - though the issue is not the circular routing, but missing "use" statement for some annotations, like Method (I just forgot to add it). Perhaps it's possible to add some more relevant error msg, since it may mislead people when trying to figure out what's wrong...?

**Comment by petforsberg** [comment]
Sorry, now I can see that I put it into Symfony CMF, while I'm using standard Symfony routing in the app. You can move it to the proper component, thx.

**Comment by lsmith77** [comment]
you need to reopen the ticket on the proper repo, we cannot move tickets. sorry.
