### ISSUE TITLE
RouteObjectInterface::getRouteKey is irrelevant

### ISSUE THREAD

**Issue by Tobion** [symfony-cmf/Routing#150]
The method `RouteObjectInterface::getRouteKey` added in #32 seems useless. According to the doc is it used to allow any chars in the route name. But this was already changed since symfony 2.2 in https://github.com/symfony/symfony/pull/6133

So getRouteKey should be deprecated or removed. And the wrong doc in http://symfony.com/doc/master/cmf/book/routing.html#linking-a-route-with-a-model-instance should be updated as well.

**Comment by dbu** [comment]
finally wanted to look into this, but i am not entirely sure. in the cmf context, we support generating a url by passing the route object and not only by passing the route name. we then use this method to get the route name as it is stored on the route object https://github.com/symfony-cmf/Routing/blob/master/ProviderBasedGenerator.php#L90 or https://github.com/symfony-cmf/Routing/blob/master/NestedMatcher/UrlMatcher.php#L49

in core symfony, the route name is only available in the RouteCollection, not on the route object itself. i am not sure whether this is enough to justify the need. the UrlMatcher situation feels a bit iffy as it points to having redundancy.

wdyt? should we keep it for the reporting in the generator and just fix the documentation, or should we really drop it?

**Comment by lsmith77** [comment]
imho lets just fix the docs and keep it .. 
its especially useful for the debugging case imho
