### ISSUE TITLE
Dynamic router not loading document in correct locale

### ISSUE THREAD

**Issue by liquorvicar** [symfony-cmf/Routing#157]
Not sure if this is a bug or the intended behaviour (or whether there is an easy fix for this) but...

We are using dynamic routing for the bulk of our site and we have multiple locales configured. Our locales are based on sub-domains (e.g. de.domain.com using the Lunetics bundle to resolve the locales). We have everything set up and working except for the fact that when we edit a translation for a document that is configured under the dynamic routing, the edits are not shown on the site (they are saved to the database). It looks like the Document is being loaded before the locale is set on the DocumentManager so the DM is loading the Document in the default language/locale.

**Comment by dbu** [comment]
this should usually work. the language is determined before loading the
routes happens afaik.

but when saving edits, the documents are saved in the locale they where
loaded from, unless something explicitly overwrites the locale on them.
we changed that in one of our projects to always use the current
language - but then it happens that a user is on the french version,
fixes a typo on an english-only page and saves... creating a "french
translation" that is the fixed english text.

the phpcr sonata admin offers a locale dropdown to explicitly set the
language being used.

did you check in phpcr what translations really exist?

**Comment by liquorvicar** [comment]
@dbu Thanks for responding. It's definitely saving the translations to phpcr correctly. The problem comes when a document that has been saved in a non-default locale is loaded via the dynamic router in the same non-default locale. In that instance, the document is loaded in the default locale rather than the non-default locale. Documents loaded manually are fine - they are loaded in the correct locale for the request. The difference seems to be that when using the dm manually, DocumentManager->LocaleChooser->Locale is set to the locale for the request when when loading via the dynamic routing then  DocumentManager->LocaleChooser->Locale is set to null, meaning that the Document passed in to the controller action as configured in the dynamic routing is for the default locale and not the locale for the request. Don't know enough about the internals to know why the locale isn't being set on the LocaleChooser when the request uses the dynamic routing.

**Comment by dbu** [comment]
try to have a look at the various event listeners from the locale
bundle, from phpcr-odm bundle and from routing. it looks like something
is out of order.

**Comment by dbu** [comment]
@liquorvicar is this still an open issue? or did you find a solution and can we close it? (would be good to hear the solution if you have one, might help other people in the future)

**Comment by liquorvicar** [comment]
@dbu Well, we found a workaround, which was to renew the document in our Controller that handles the dynamic requests:
```
    /**
     * @param BasicPage $contentDocument
     * @return Response
     */
    public function pageAction(BasicPage $contentDocument)
    {
        /**
         * We need to renew the document here as the dynamic routing loads the document using the default locale and
         * not the locale from the request
         */
        $contentDocument = $this->documentLibrary->renew($contentDocument);

        return $this->templating->renderResponse(
            'ApplicationBundle:Default:' . $contentDocument->getTemplate() . '.html.twig',
            array(
                'cmfMainContent'  => $contentDocument,
            )
        );
    }
```
where $documentLibrary::renew() is
```
    /**
     * @param BasicPage $document
     * @return BasicPage
     */
    public function renew(BasicPage $document)
    {
        $this->dm->clear();
        return $this->dm->find(BasicPage::class, $document->getId());
    }
```

I've looked into it a bit further and it looks like the actual problem is that the Document is loaded during the routing (in \Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RouteProvider::getRouteCollectionForRequest) whereas the locale for the current request doesn't get set until \Doctrine\Bundle\PHPCRBundle\EventListener\LocaleListener::onKernelRequest which happens after the routing. Thus at the point the Document gets loaded from the DM the LocaleChooser in the DM doesn't have access to the locale from the current request.

I don't really know enough about the internals of Symfony to know what happens next and how this could be fixed...

**Comment by dbu** [comment]
is your route document the content document? or does it use a reference?

or would the problem occur during RouteContentEnhancer::enhance?

oh, one more idea: did you disable proxies for some reason? afaik if the content is not the same as the route document, it should be a proxy. in this case, i think the proxy is requested without specific locale, which gives you a proxy that will resolve the locale that is valid when it is first accessed. could it be that you have something that accesses a field of the content (thus triggering the proxy to load) before the LocaleListener triggers?

**Comment by liquorvicar** [comment]
It seems to be the object manager in \Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RouteProvider::getRouteCollectionForRequest that's returning the actual document and not a proxy here:
```
            /** @var $dm DocumentManager */
            $dm = $this->getObjectManager();
            $routes = $dm->findMany($this->className, $candidates);
```
As far as I know we haven't disabled the proxies. How would I check that?

**Comment by dbu** [comment]
proxies are only for when you do $route->getContent(), not the document
returned by find() directly. is your Route class also the Content class?
does the getContent method of your class say `return $this` or `return
$this->content`? are you using your own documents or extending some CMF
document?

**Comment by liquorvicar** [comment]
Our documents extend \Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page

**Comment by dbu** [comment]
okay, then it makes sense. the document is loaded at a point where the locale is not yet known, and you need to reload it to get the desired language.

does this mean your urls are /en/my-english-name and /fr/my-english-name (or whatever your locales are)? do you use the `add_locale_pattern` option (resp the deprecated setAddLocalePattern method)?

**Comment by liquorvicar** [comment]
We actually use sub-domains to separate the locales so (e.g.) en.domain.com/my-english-name and fr.domain.com/my-english-name etc

We don't use `add_locale_pattern` AFAIK

**Comment by dbu** [comment]
ah, right that is another solution. hm, if you never have the case where the specific route changes the locale, you might look how to have the locale decision and the phpcr-odm locale listener come before the routing. you could disable the phpcr-odm provided listener and write your own that comes with a high priority and maps the domain to locale, then sets that on the phpcr-odm manager. then the content should be in the correct locale already. i hope routing does not destroy the locale that is already set, you might need to check the details there.

(you could then probably also remove the Lunetics LocaleBundle if you use that, as it mainly provides flexibility for various situations.)

**Comment by dbu** [comment]
@liquorvicar did you have a look at this? is there anything i can help you with or is it ok to close this issue?

**Comment by liquorvicar** [comment]
The proxy behaviour you described above sounds interesting. Is there a way to configure it to load a proxy first and only load the locale-specific document when it needs it?

FWIW, our current workaround is probably sufficient for now. Also, I'm leaving this project next Tues (9th Feb) and will probably not be working with Symfony or even PHP so might not have much time to contribute here. Given that, I have no objections to you closing the issue if you feel that's appropriate ;-)

**Comment by dbu** [comment]
the proxy is not only about locales, but about the whole document. with simplecms, that the route is at the same time the content, so a proxy does not help. options i see:

- use ContentBundle content with separate routes per locale
- build your own locale listener that sets the locale before the routing even happens
- build your own route document that is not translated (probably extending the RoutingBundle document) but has a child "content" that is translated - this should be able to be a proxy, like with the references the RoutingBundle route document uses.

i will leave this open for a moment and try to see if we can update the documentation to better explain the situation.

**Comment by dbu** [comment]
see https://github.com/symfony-cmf/symfony-cmf-docs/pull/737
