### ISSUE TITLE
`getRouteByName()` without `parameters` in the `RouteProviderInterface` is useless

### ISSUE THREAD

**Issue by saimaz** [symfony-cmf/Routing#160]
When you want use a custom provider to match and generate routes dynamically it's very useful to have parameters to pass an object or any other parameter to generate the url. Right now I think there is a logic problem in the code where some functions conflicts with the `RouteProviderInterface` interface.

e.g. like here https://github.com/symfony-cmf/Routing/blob/6d318f97b86f424cf740e4883a8099b18192e136/ProviderBasedGenerator.php#L53

Generate function cannot call provider's `getRouteByName` because `RouteProviderInterface` interface doesn't let to add parameters. 

I propose to return parameters to the `RouteProviderInterface` `getRouteByName` function. If you think that makes sense I could do a PR to fix this issue.

**Comment by saimaz** [comment]
btw, I'm trying to use Routing component not with the symfony-cmf, and want to use only route provider. Sadly when there is no parameter variable passing I must create custom url generator and leave those two functions (`getRouteByName`, `getRoutesByNames`) empty.

**Comment by dbu** [comment]
hi @saimaz , glad if the routing component is useful to you. the getRouteByName call you linked to indeed looks weird. it seems to be a leftover that has been cleaned up on the provider side: https://github.com/symfony-cmf/RoutingBundle/commit/029ae8291fa71016d282e1907af6bfc8a80bbe76

i don't understand why you need the parameters to identify the route object. the name of a route should be unique and clearly identify what route object has to be loaded. the parameters *are* used for the actual generation of the URL from the route object, see https://github.com/symfony-cmf/Routing/blob/6d318f97b86f424cf740e4883a8099b18192e136/ProviderBasedGenerator.php#L63

if you want to generate route objects on the fly based on the parameters, i would look into replacing/extending the ProviderBasedGenerator instead.

**Comment by saimaz** [comment]
Thanks for the explanation about route generation. Dynamically generate routes by replacing/extending `ProviderBasedGenerator` makes sense.

**Comment by dbu** [comment]
great. just for terminology: route (in the context of this library) is the `Route` object. URL is a string that is a concrete URL. a parametrized route may represent many URLs. this library handles generating URLs from Route objects, not generating (or creating on the fly) `Route` objects. in your usecase, do you really create route objects on the fly? would be interesting to read the use case you have.

**Comment by saimaz** [comment]
Well, the terminology is a bit different than usual. But now I got it and will adapt to our work. 

So the use case. I'm working on a project called ONGR, it's a bunch of Symfony bundles to provide faster development for e-commerce, meta site search and other websites with the Elasticsearch. There is not so much to talk, please take a look at those bundles :). 

Our RouterBundle which is based on Routing component https://github.com/ongr-io/RouterBundle.
ElasticsearchBundle https://github.com/ongr-io/ElasticsearchBundle and the rest https://github.com/ongr-io

With all our bundles we are very close to release a stable 1.0 versions. So IMO it's going to be a great bundles :).

**Comment by dbu** [comment]
ah, cool! i saw a talk about ongr at symfony live in berlin, i think in november 2014. glad to hear you make progress! don't hesitate to ask me if you need further help to leverage cmf components.
