### ISSUE TITLE
Issues with conditional enhancer

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/Routing#176]
To explain #175 and describe the problems with the conditional enhancer:
### Can't inject objects by DI container

Late, but when implementing the extension in routing bundle to use the conditional enhancer, i realized, that an enhancer map containing the objects of matcher and enhancer won't work as the DI container does not like any objects (dumping into xml problems). 
That was the reason to create #175 Currently i am not sure if i need the implemented `priority` - cause of the second problem
### Every class/type/<item> needs an own conditional enhancer

I would just start with an example:

```

        controllers_by_type:
            demo_alias: 
              -
                methods: ['put', 'post']
                value: test.controller:aliasAction
        controllers_by_class:
            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:
              -
                methods: ['put', 'post']
                value: cmf_routing.redirect_controller:redirectAction
            Symfony\Cmf\Bundle\RoutingBundle\Tests\Resources\Document\Content:
              - 
                methods: ['post', 'put']
                value: service:putAction
        templates_by_class:
            Symfony\Cmf\Bundle\RoutingBundle\Tests\Resources\Document\Content: TestBundle:Content:index.html.twig
```

without that method mapping that would leed to 4 different enhancers. 3 FieldByClass (controller_by_class, controller_by_type, controller_for_template_by_class) and 1 FieldMapPre.. 

i.e. PUT request:
I can't put the complete configuration into one conditional enhancer. The first request match would close the chain even when the enhancer except _type = demo_alias => _controller = test.controller:aliasAction.
So would need to create 3 different conditional ehnacers. One vor the target pair _type/_controller _content/_controller and one for null/_template. The _content/_controller pair can go of controller_for_template_by_class and controller_by_class can go in one - they have the same target/source pair - i thought. But again: The first request match would close the chain completely independent from the work of the enhancer.
So lets to a 4th conditional enhancer to put especially controller_by_class into one map. But lets expect a PUT request again on a route with content of class Symfony\Cmf\Bundle\RoutingBundle\Tests\Resources\Document\Content. The request matcher would close agein on the first entry the FieldByClass enhancer will see that the current content is of class Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute and would do nothing. Chain closed :-(

So The only way to work with the conditional enhancer is by creating one for each type/class/<item> to just find the first request match. So i would create 5 different conditional enhancers for the current example. I don't know if that is a step forward. Is that the way we planned it @dbu? From the point of seperating concerns it is really good but from the performance view we instantiate two times classes as before.

**Comment by dbu** [comment]
is this still relevant?

**Comment by ElectricMaxxx** [comment]
reopened a PR to test it.

**Comment by dbu** [comment]
what if we remove the ConditionalEnhancer in 2.0 and add it back in in 2.1 with something that we are sure works? i am not exactly sure to understand all of the implications, though i still feel like it should be possible to achieve your scenario with the existing ConditionalEnhancer.

i really want to release asap, and adding a new class will not be a BC break. however, having this class with a problematic design would be a problem for the future
