### ISSUE TITLE
No Deprication

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/routing#177]

**Comment by ElectricMaxxx** [comment]
@dbu is that still relevant, do found some deprecations?

**Comment by wouterj** [comment]
At least the `match()` method of the router IIRC

**Comment by dbu** [comment]
found no deprecations but a bunch of things. see #184

**Comment by wouterj** [comment]
@dbu what about https://github.com/symfony-cmf/routing/blob/master/src/DynamicRouter.php#L227 ?

**Comment by dbu** [comment]
#116 is the only open question here.
