### ISSUE TITLE
Print dynamic routes on router:debug

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/routing#199]
I think it wouldn't that complicated to ask all items of the chain-router, when asking for the routes, isn't it?

**Comment by dbu** [comment]
thats already implemented: https://github.com/symfony-cmf/routing/blob/d4fa611c200b47f81031dd34adc96ed5ed4c087c/src/ChainRouter.php#L334

the dynamic router however is configured to not return its routes by default. it could return thousands of routes, depending on the repository. therefore it defaults to not return routes, but you can enable it. see the block right above https://symfony.com/doc/current/cmf/bundles/routing/dynamic.html#handling-redirectroutes

**Comment by ElectricMaxxx** [comment]
Thanks.
