### ISSUE TITLE
Redirect routes with trailing slash

### ISSUE THREAD

**Issue by EmmanuelVella** [symfony-cmf/Routing#247]
## Subject

Hi here !

I just upgraded my app from symfony 3.4 to 4.4, and I have an issue with trailing slashes. In symfony 3.4, I used [this method](https://symfony.com/doc/3.4/routing/redirect_trailing_slash.html) which worked well.

But since symfony 4.1 and the new trailing slashes handling, I get an infinite loop when trying to match a cmf route with a trailing slash. Removing the custom redirect action works, but cmf urls with trailing slashes are not redirected anymore.

## Steps to reproduce

Use symfony 4.1+, and try to match a cmf route ending with an url with a trailing slash.

## Expected results

I should be redirected to the same url without the trailing slash.

## Actual results

I get a 404.

**Comment by dbu** [comment]
hi emmanuel, long time no see :wave:

yeah, unless you store the route with the flag to have a trailing `/`, it will not be matched. if i understand https://symfony.com/doc/4.1/routing.html#routing-trailing-slash-redirection correctly, they now automatically redirect, but only if the route without a slash has been found. we could implement the same in the cmf route matcher (we already have the logic to see if [the flag](https://github.com/symfony-cmf/routing-bundle/blob/513c269adb2d72bd5daf309d343374bf396be8c2/src/Doctrine/Phpcr/Route.php#L65) that a route is supposed to have a trailing slash) - i assume the only difference is that we would need to also provide the inverse logic to redirect removing the slash if no trailing slash is wanted. the [candidates class](https://github.com/symfony-cmf/Routing/blob/12f3f64a0ab89ee0dc5ead8802167de762eac024/src/Candidates/Candidates.php#L141) has the logic to strip trailing slashes. 

i would assume that we need something in the [UrlMatcher](https://github.com/symfony-cmf/Routing/blob/master/src/NestedMatcher/UrlMatcher.php) to find out that we need to redirect, or in DynamicRouter - i am not sure at which level core symfony does the redirection, but think that we should do it on the same level.

do you want to do a pull request for that?

**Comment by dannyvw** [comment]
Is there any update for this?

**Comment by dbu** [comment]
i don't think anyone worked on it, no. want to give it a shot?

**Comment by EmmanuelVella** [comment]
Hi all ! Sorry, I just wanted to report the issue, I would be glad to help but unfortunately I have no time for this.

**Comment by dbu** [comment]
no worries @EmmanuelVella , reporting also helps. maybe @dannyvw wants to work on it?

**Comment by dannyvw** [comment]
After some debugging it looks like it is no problem in cmf routing bundle for us.

**Comment by dbu** [comment]
fixed in #465
